
server:
  port: 8089

spring:
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  messages:
    basename: i18n/messages

  data:
    mongodb:
#      uri: mongodb://memone:OpenSesame!@192.168.1.241:27017/memone
      uri: mongodb://memone:OpenSesame!@192.168.16.54:27017/memone