
server:
  port: 8089

spring:
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
+